version: "3.9"
services:
  backend:
    build: .
    command: sh entrypoint.sh
    env_file: ".env"
    volumes:
    - .:/backend:rw
    depends_on:
    - db

  db:
    hostname: db
    image: postgres:14-alpine
    restart: always
    env_file: ".env"
    volumes:
      - ./db_data:/var/lib/postgresql/data/:rw

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: watchmedo auto-restart -d . -p '*.py' -- celery -A project worker -l info
    env_file: ".env"
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: watchmedo auto-restart -d . -p '*.py' -- celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: ".env"
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email miczicherry@gmail.com -d api.mwis.pl --agree-tos
    depends_on:
      - nginx

volumes:
  db_data:
  nginx_secrets:
