version: "3.9"
services:
  backend:
    build: .
    command: sh entrypoint.sh
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
    - .:/backend:rw
    depends_on:
    - db
    - redis

  db:
    hostname: db
    image: postgres:14-alpine
    restart: always
    env_file: ".env"
    volumes:
      - db_data:/var/lib/postgresql/data/:rw

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "10050:80"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: watchmedo auto-restart -d . -p '*.py' -- celery -A project worker -l info
    env_file: ".env"
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: watchmedo auto-restart -d . -p '*.py' -- celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: ".env"
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis

volumes:
  db_data:
