# Generated by Django 3.2.12 on 2022-04-05 09:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skarbonka', '0002_auto_20220325_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='day_of_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resource', models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Transaction'), (3, 'Allowance')], default=1)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
