# Generated by Django 3.2.12 on 2022-04-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('skarbonka', '0004_auto_20220405_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notify',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.clockedschedule'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Granted'), (3, 'Declined'), (4, 'Paid off')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resource',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Transaction'), (3, 'Allowance'), (4, 'Loan')], default=1),
        ),
    ]
