# Generated by Django 3.2.12 on 2022-05-15 10:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('skarbonka', '0006_auto_20220426_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[(1, 'Accepted'), (2, 'Pending'), (3, 'Failed'), (4, 'Declined')], default=2, max_length=50),
        ),
    ]
