# Generated by Django 3.2.12 on 2022-05-15 14:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('skarbonka', '0008_auto_20220515_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('1', 'Accepted'), ('2', 'Pending'), ('3', 'Failed'), ('4', 'Declined'), ('5', 'Require Confirmation')], default='2', max_length=50),
        ),
    ]
