# Generated by Django 3.2.12 on 2022-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skarbonka', '0009_alter_transaction_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
