# Generated by Django 3.2.12 on 2022-05-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('skarbonka', '0011_auto_20220517_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='notify',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
