# Generated by Django 3.2.12 on 2022-05-31 09:08

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('skarbonka', '0012_alter_loan_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='state',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_state',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Pending'), (2, 'Granted'), (3, 'Declined'), (4, 'Paid off'), (5, 'Expired')], default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='notify',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[('1', 'Accepted'), ('2', 'Pending'), ('3', 'Failed'), ('4', 'Declined'), ('5', 'Require Confirmation')], default='2'),
        ),
    ]
