# Generated by Django 3.2.12 on 2022-05-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220426_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
    ]
